use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Element {
    pub atomic_number: u8,
    pub symbol: &'static str,
    pub name: &'static str,
    pub pronunciation: &'static str,
    pub english_name: &'static str,
    pub atomic_weight: f64,
    pub period: u8,
    pub group: &'static str,
}

pub const PERIODIC_TABLE: &[Element] = &[
    // 周期1（2种）
    Element { atomic_number: 1, symbol: "H", name: "氢", pronunciation: "qīng", english_name: "Hydrogen", atomic_weight: 1.008, period: 1, group: "IA" },
    Element { atomic_number: 2, symbol: "He", name: "氦", pronunciation: "hài", english_name: "Helium", atomic_weight: 4.0026, period: 1, group: "0族" },
    
    // 周期2（8种）
    Element { atomic_number: 3, symbol: "Li", name: "锂", pronunciation: "lǐ", english_name: "Lithium", atomic_weight: 6.941, period: 2, group: "IA" },
    Element { atomic_number: 4, symbol: "Be", name: "铍", pronunciation: "pí", english_name: "Beryllium", atomic_weight: 9.0122, period: 2, group: "IIA" },
    Element { atomic_number: 5, symbol: "B", name: "硼", pronunciation: "péng", english_name: "Boron", atomic_weight: 10.811, period: 2, group: "IIIA" },
    Element { atomic_number: 6, symbol: "C", name: "碳", pronunciation: "tàn", english_name: "Carbon", atomic_weight: 12.011, period: 2, group: "IVA" },
    Element { atomic_number: 7, symbol: "N", name: "氮", pronunciation: "dàn", english_name: "Nitrogen", atomic_weight: 14.007, period: 2, group: "VA" },
    Element { atomic_number: 8, symbol: "O", name: "氧", pronunciation: "yǎng", english_name: "Oxygen", atomic_weight: 15.999, period: 2, group: "VIA" },
    Element { atomic_number: 9, symbol: "F", name: "氟", pronunciation: "fú", english_name: "Fluorine", atomic_weight: 18.998, period: 2, group: "VIIA" },
    Element { atomic_number: 10, symbol: "Ne", name: "氖", pronunciation: "nǎi", english_name: "Neon", atomic_weight: 20.180, period: 2, group: "0族" },
    
    // 周期3（8种）
    Element { atomic_number: 11, symbol: "Na", name: "钠", pronunciation: "nà", english_name: "Sodium", atomic_weight: 22.990, period: 3, group: "IA" },
    Element { atomic_number: 12, symbol: "Mg", name: "镁", pronunciation: "měi", english_name: "Magnesium", atomic_weight: 24.305, period: 3, group: "IIA" },
    Element { atomic_number: 13, symbol: "Al", name: "铝", pronunciation: "lǚ", english_name: "Aluminum", atomic_weight: 26.982, period: 3, group: "IIIA" },
    Element { atomic_number: 14, symbol: "Si", name: "硅", pronunciation: "guī", english_name: "Silicon", atomic_weight: 28.085, period: 3, group: "IVA" },
    Element { atomic_number: 15, symbol: "P", name: "磷", pronunciation: "lín", english_name: "Phosphorus", atomic_weight: 30.974, period: 3, group: "VA" },
    Element { atomic_number: 16, symbol: "S", name: "硫", pronunciation: "liú", english_name: "Sulfur", atomic_weight: 32.06, period: 3, group: "VIA" },
    Element { atomic_number: 17, symbol: "Cl", name: "氯", pronunciation: "lǜ", english_name: "Chlorine", atomic_weight: 35.45, period: 3, group: "VIIA" },
    Element { atomic_number: 18, symbol: "Ar", name: "氩", pronunciation: "yà", english_name: "Argon", atomic_weight: 39.948, period: 3, group: "0族" },
    
    // 周期4（18种）
    Element { atomic_number: 19, symbol: "K", name: "钾", pronunciation: "jiǎ", english_name: "Potassium", atomic_weight: 39.098, period: 4, group: "IA" },
    Element { atomic_number: 20, symbol: "Ca", name: "钙", pronunciation: "gài", english_name: "Calcium", atomic_weight: 40.078, period: 4, group: "IIA" },
    Element { atomic_number: 21, symbol: "Sc", name: "钪", pronunciation: "kàng", english_name: "Scandium", atomic_weight: 44.956, period: 4, group: "IIIB" },
    Element { atomic_number: 22, symbol: "Ti", name: "钛", pronunciation: "tài", english_name: "Titanium", atomic_weight: 47.867, period: 4, group: "IVB" },
    Element { atomic_number: 23, symbol: "V", name: "钒", pronunciation: "fán", english_name: "Vanadium", atomic_weight: 50.942, period: 4, group: "VB" },
    Element { atomic_number: 24, symbol: "Cr", name: "铬", pronunciation: "gè", english_name: "Chromium", atomic_weight: 51.996, period: 4, group: "VIB" },
    Element { atomic_number: 25, symbol: "Mn", name: "锰", pronunciation: "měng", english_name: "Manganese", atomic_weight: 54.938, period: 4, group: "VIIB" },
    Element { atomic_number: 26, symbol: "Fe", name: "铁", pronunciation: "tiě", english_name: "Iron", atomic_weight: 55.845, period: 4, group: "VIIIB" },
    Element { atomic_number: 27, symbol: "Co", name: "钴", pronunciation: "gǔ", english_name: "Cobalt", atomic_weight: 58.933, period: 4, group: "VIIIB" },
    Element { atomic_number: 28, symbol: "Ni", name: "镍", pronunciation: "niè", english_name: "Nickel", atomic_weight: 58.693, period: 4, group: "VIIIB" },
    Element { atomic_number: 29, symbol: "Cu", name: "铜", pronunciation: "tóng", english_name: "Copper", atomic_weight: 63.546, period: 4, group: "IB" },
    Element { atomic_number: 30, symbol: "Zn", name: "锌", pronunciation: "xīn", english_name: "Zinc", atomic_weight: 65.38, period: 4, group: "IIB" },
    Element { atomic_number: 31, symbol: "Ga", name: "镓", pronunciation: "jiā", english_name: "Gallium", atomic_weight: 69.723, period: 4, group: "IIIA" },
    Element { atomic_number: 32, symbol: "Ge", name: "锗", pronunciation: "zhě", english_name: "Germanium", atomic_weight: 72.63, period: 4, group: "IVA" },
    Element { atomic_number: 33, symbol: "As", name: "砷", pronunciation: "shēn", english_name: "Arsenic", atomic_weight: 74.922, period: 4, group: "VA" },
    Element { atomic_number: 34, symbol: "Se", name: "硒", pronunciation: "xī", english_name: "Selenium", atomic_weight: 78.971, period: 4, group: "VIA" },
    Element { atomic_number: 35, symbol: "Br", name: "溴", pronunciation: "xiù", english_name: "Bromine", atomic_weight: 79.904, period: 4, group: "VIIA" },
    Element { atomic_number: 36, symbol: "Kr", name: "氪", pronunciation: "kè", english_name: "Krypton", atomic_weight: 83.798, period: 4, group: "0族" },
    
    // 周期5（18种）
    Element { atomic_number: 37, symbol: "Rb", name: "铷", pronunciation: "rú", english_name: "Rubidium", atomic_weight: 85.468, period: 5, group: "IA" },
    Element { atomic_number: 38, symbol: "Sr", name: "锶", pronunciation: "sī", english_name: "Strontium", atomic_weight: 87.62, period: 5, group: "IIA" },
    Element { atomic_number: 39, symbol: "Y", name: "钇", pronunciation: "yǐ", english_name: "Yttrium", atomic_weight: 88.906, period: 5, group: "IIIB" },
    Element { atomic_number: 40, symbol: "Zr", name: "锆", pronunciation: "gào", english_name: "Zirconium", atomic_weight: 91.224, period: 5, group: "IVB" },
    Element { atomic_number: 41, symbol: "Nb", name: "铌", pronunciation: "ní", english_name: "Niobium", atomic_weight: 92.906, period: 5, group: "VB" },
    Element { atomic_number: 42, symbol: "Mo", name: "钼", pronunciation: "mù", english_name: "Molybdenum", atomic_weight: 95.95, period: 5, group: "VIB" },
    Element { atomic_number: 43, symbol: "Tc", name: "锝", pronunciation: "dé", english_name: "Technetium", atomic_weight: 98.0, period: 5, group: "VIIB" },
    Element { atomic_number: 44, symbol: "Ru", name: "钌", pronunciation: "liǎo", english_name: "Ruthenium", atomic_weight: 101.07, period: 5, group: "VIIIB" },
    Element { atomic_number: 45, symbol: "Rh", name: "铑", pronunciation: "láo", english_name: "Rhodium", atomic_weight: 102.91, period: 5, group: "VIIIB" },
    Element { atomic_number: 46, symbol: "Pd", name: "钯", pronunciation: "bǎ", english_name: "Palladium", atomic_weight: 106.42, period: 5, group: "VIIIB" },
    Element { atomic_number: 47, symbol: "Ag", name: "银", pronunciation: "yín", english_name: "Silver", atomic_weight: 107.87, period: 5, group: "IB" },
    Element { atomic_number: 48, symbol: "Cd", name: "镉", pronunciation: "gé", english_name: "Cadmium", atomic_weight: 112.41, period: 5, group: "IIB" },
    Element { atomic_number: 49, symbol: "In", name: "铟", pronunciation: "yīn", english_name: "Indium", atomic_weight: 114.82, period: 5, group: "IIIA" },
    Element { atomic_number: 50, symbol: "Sn", name: "锡", pronunciation: "xī", english_name: "Tin", atomic_weight: 118.71, period: 5, group: "IVA" },
    Element { atomic_number: 51, symbol: "Sb", name: "锑", pronunciation: "tī", english_name: "Antimony", atomic_weight: 121.76, period: 5, group: "VA" },
    Element { atomic_number: 52, symbol: "Te", name: "碲", pronunciation: "dì", english_name: "Tellurium", atomic_weight: 127.6, period: 5, group: "VIA" },
    Element { atomic_number: 53, symbol: "I", name: "碘", pronunciation: "diǎn", english_name: "Iodine", atomic_weight: 126.9, period: 5, group: "VIIA" },
    Element { atomic_number: 54, symbol: "Xe", name: "氙", pronunciation: "xiān", english_name: "Xenon", atomic_weight: 131.29, period: 5, group: "0族" },
    
    // 周期6（32种）
    Element { atomic_number: 55, symbol: "Cs", name: "铯", pronunciation: "sè", english_name: "Cesium", atomic_weight: 132.91, period: 6, group: "IA" },
    Element { atomic_number: 56, symbol: "Ba", name: "钡", pronunciation: "bèi", english_name: "Barium", atomic_weight: 137.33, period: 6, group: "IIA" },
    Element { atomic_number: 57, symbol: "La", name: "镧", pronunciation: "lán", english_name: "Lanthanum", atomic_weight: 138.91, period: 6, group: "IIIB" },
    Element { atomic_number: 58, symbol: "Ce", name: "铈", pronunciation: "shì", english_name: "Cerium", atomic_weight: 140.12, period: 6, group: "镧系" },
    Element { atomic_number: 59, symbol: "Pr", name: "镨", pronunciation: "pǔ", english_name: "Praseodymium", atomic_weight: 140.91, period: 6, group: "镧系" },
    Element { atomic_number: 60, symbol: "Nd", name: "钕", pronunciation: "nǚ", english_name: "Neodymium", atomic_weight: 144.24, period: 6, group: "镧系" },
    Element { atomic_number: 61, symbol: "Pm", name: "钷", pronunciation: "pǒ", english_name: "Promethium", atomic_weight: 145.0, period: 6, group: "镧系" },
    Element { atomic_number: 62, symbol: "Sm", name: "钐", pronunciation: "shān", english_name: "Samarium", atomic_weight: 150.36, period: 6, group: "镧系" },
    Element { atomic_number: 63, symbol: "Eu", name: "铕", pronunciation: "yǒu", english_name: "Europium", atomic_weight: 151.96, period: 6, group: "镧系" },
    Element { atomic_number: 64, symbol: "Gd", name: "钆", pronunciation: "gá", english_name: "Gadolinium", atomic_weight: 157.25, period: 6, group: "镧系" },
    Element { atomic_number: 65, symbol: "Tb", name: "铽", pronunciation: "tè", english_name: "Terbium", atomic_weight: 158.93, period: 6, group: "镧系" },
    Element { atomic_number: 66, symbol: "Dy", name: "镝", pronunciation: "dī", english_name: "Dysprosium", atomic_weight: 162.50, period: 6, group: "镧系" },
    Element { atomic_number: 67, symbol: "Ho", name: "钬", pronunciation: "huǒ", english_name: "Holmium", atomic_weight: 164.93, period: 6, group: "镧系" },
    Element { atomic_number: 68, symbol: "Er", name: "铒", pronunciation: "ěr", english_name: "Erbium", atomic_weight: 167.26, period: 6, group: "镧系" },
    Element { atomic_number: 69, symbol: "Tm", name: "铥", pronunciation: "diū", english_name: "Thulium", atomic_weight: 168.93, period: 6, group: "镧系" },
    Element { atomic_number: 70, symbol: "Yb", name: "镱", pronunciation: "yì", english_name: "Ytterbium", atomic_weight: 173.05, period: 6, group: "镧系" },
    Element { atomic_number: 71, symbol: "Lu", name: "镥", pronunciation: "lǔ", english_name: "Lutetium", atomic_weight: 174.97, period: 6, group: "镧系" },
    Element { atomic_number: 72, symbol: "Hf", name: "铪", pronunciation: "hā", english_name: "Hafnium", atomic_weight: 178.49, period: 6, group: "IVB" },
    Element { atomic_number: 73, symbol: "Ta", name: "钽", pronunciation: "tǎn", english_name: "Tantalum", atomic_weight: 180.95, period: 6, group: "VB" },
    Element { atomic_number: 74, symbol: "W", name: "钨", pronunciation: "wū", english_name: "Tungsten", atomic_weight: 183.84, period: 6, group: "VIB" },
    Element { atomic_number: 75, symbol: "Re", name: "铼", pronunciation: "lái", english_name: "Rhenium", atomic_weight: 186.21, period: 6, group: "VIIB" },
    Element { atomic_number: 76, symbol: "Os", name: "锇", pronunciation: "é", english_name: "Osmium", atomic_weight: 190.23, period: 6, group: "VIIIB" },
    Element { atomic_number: 77, symbol: "Ir", name: "铱", pronunciation: "yī", english_name: "Iridium", atomic_weight: 192.22, period: 6, group: "VIIIB" },
    Element { atomic_number: 78, symbol: "Pt", name: "铂", pronunciation: "bó", english_name: "Platinum", atomic_weight: 195.08, period: 6, group: "VIIIB" },
    Element { atomic_number: 79, symbol: "Au", name: "金", pronunciation: "jīn", english_name: "Gold", atomic_weight: 196.97, period: 6, group: "IB" },
    Element { atomic_number: 80, symbol: "Hg", name: "汞", pronunciation: "gǒng", english_name: "Mercury", atomic_weight: 200.59, period: 6, group: "IIB" },
    Element { atomic_number: 81, symbol: "Tl", name: "铊", pronunciation: "tā", english_name: "Thallium", atomic_weight: 204.38, period: 6, group: "IIIA" },
    Element { atomic_number: 82, symbol: "Pb", name: "铅", pronunciation: "qiān", english_name: "Lead", atomic_weight: 207.2, period: 6, group: "IVA" },
    Element { atomic_number: 83, symbol: "Bi", name: "铋", pronunciation: "bì", english_name: "Bismuth", atomic_weight: 208.98, period: 6, group: "VA" },
    Element { atomic_number: 84, symbol: "Po", name: "钋", pronunciation: "pō", english_name: "Polonium", atomic_weight: 209.0, period: 6, group: "VIA" },
    Element { atomic_number: 85, symbol: "At", name: "砹", pronunciation: "ài", english_name: "Astatine", atomic_weight: 210.0, period: 6, group: "VIIA" },
    Element { atomic_number: 86, symbol: "Rn", name: "氡", pronunciation: "dōng", english_name: "Radon", atomic_weight: 222.0, period: 6, group: "0族" },
    
    // 周期7（32种）
    Element { atomic_number: 87, symbol: "Fr", name: "钫", pronunciation: "fāng", english_name: "Francium", atomic_weight: 223.0, period: 7, group: "IA" },
    Element { atomic_number: 88, symbol: "Ra", name: "镭", pronunciation: "léi", english_name: "Radium", atomic_weight: 226.0, period: 7, group: "IIA" },
    Element { atomic_number: 89, symbol: "Ac", name: "锕", pronunciation: "ā", english_name: "Actinium", atomic_weight: 227.0, period: 7, group: "IIIB" },
    Element { atomic_number: 90, symbol: "Th", name: "钍", pronunciation: "tǔ", english_name: "Thorium", atomic_weight: 232.04, period: 7, group: "锕系" },
    Element { atomic_number: 91, symbol: "Pa", name: "镤", pronunciation: "pú", english_name: "Protactinium", atomic_weight: 231.04, period: 7, group: "锕系" },
    Element { atomic_number: 92, symbol: "U", name: "铀", pronunciation: "yóu", english_name: "Uranium", atomic_weight: 238.03, period: 7, group: "锕系" },
    Element { atomic_number: 93, symbol: "Np", name: "镎", pronunciation: "ná", english_name: "Neptunium", atomic_weight: 237.0, period: 7, group: "锕系" },
    Element { atomic_number: 94, symbol: "Pu", name: "钚", pronunciation: "bù", english_name: "Plutonium", atomic_weight: 244.0, period: 7, group: "锕系" },
    Element { atomic_number: 95, symbol: "Am", name: "镅", pronunciation: "méi", english_name: "Americium", atomic_weight: 243.0, period: 7, group: "锕系" },
    Element { atomic_number: 96, symbol: "Cm", name: "锔", pronunciation: "jú", english_name: "Curium", atomic_weight: 247.0, period: 7, group: "锕系" },
    Element { atomic_number: 97, symbol: "Bk", name: "锫", pronunciation: "péi", english_name: "Berkelium", atomic_weight: 247.0, period: 7, group: "锕系" },
    Element { atomic_number: 98, symbol: "Cf", name: "锎", pronunciation: "kāi", english_name: "Californium", atomic_weight: 251.0, period: 7, group: "锕系" },
    Element { atomic_number: 99, symbol: "Es", name: "锿", pronunciation: "āi", english_name: "Einsteinium", atomic_weight: 252.0, period: 7, group: "锕系" },
    Element { atomic_number: 100, symbol: "Fm", name: "镄", pronunciation: "fèi", english_name: "Fermium", atomic_weight: 257.0, period: 7, group: "锕系" },
    Element { atomic_number: 101, symbol: "Md", name: "钔", pronunciation: "mén", english_name: "Mendelevium", atomic_weight: 258.0, period: 7, group: "锕系" },
    Element { atomic_number: 102, symbol: "No", name: "锘", pronunciation: "nuò", english_name: "Nobelium", atomic_weight: 259.0, period: 7, group: "锕系" },
    Element { atomic_number: 103, symbol: "Lr", name: "铹", pronunciation: "láo", english_name: "Lawrencium", atomic_weight: 262.0, period: 7, group: "锕系" },
    Element { atomic_number: 104, symbol: "Rf", name: "𬬻", pronunciation: "lú", english_name: "Rutherfordium", atomic_weight: 267.0, period: 7, group: "IVB" },
    Element { atomic_number: 105, symbol: "Db", name: "𬭊", pronunciation: "dù", english_name: "Dubnium", atomic_weight: 268.0, period: 7, group: "VB" },
    Element { atomic_number: 106, symbol: "Sg", name: "𬭳", pronunciation: "xǐ", english_name: "Seaborgium", atomic_weight: 271.0, period: 7, group: "VIB" },
    Element { atomic_number: 107, symbol: "Bh", name: "𬭛", pronunciation: "bō", english_name: "Bohrium", atomic_weight: 272.0, period: 7, group: "VIIB" },
    Element { atomic_number: 108, symbol: "Hs", name: "𬭶", pronunciation: "hēi", english_name: "Hassium", atomic_weight: 270.0, period: 7, group: "VIIIB" },
    Element { atomic_number: 109, symbol: "Mt", name: "鿏", pronunciation: "mài", english_name: "Meitnerium", atomic_weight: 276.0, period: 7, group: "VIIIB" },
    Element { atomic_number: 110, symbol: "Ds", name: "𫟼", pronunciation: "dá", english_name: "Darmstadtium", atomic_weight: 281.0, period: 7, group: "VIIIB" },
    Element { atomic_number: 111, symbol: "Rg", name: "𬬭", pronunciation: "lún", english_name: "Roentgenium", atomic_weight: 280.0, period: 7, group: "IB" },
    Element { atomic_number: 112, symbol: "Cn", name: "鿔", pronunciation: "gē", english_name: "Copernicium", atomic_weight: 285.0, period: 7, group: "IIB" },
    Element { atomic_number: 113, symbol: "Nh", name: "鿭", pronunciation: "nǐ", english_name: "Nihonium", atomic_weight: 284.0, period: 7, group: "IIIA" },
    Element { atomic_number: 114, symbol: "Fl", name: "𫓧", pronunciation: "fū", english_name: "Flerovium", atomic_weight: 289.0, period: 7, group: "IVA" },
    Element { atomic_number: 115, symbol: "Mc", name: "镆", pronunciation: "mò", english_name: "Moscovium", atomic_weight: 288.0, period: 7, group: "VA" },
    Element { atomic_number: 116, symbol: "Lv", name: "𫟷", pronunciation: "lì", english_name: "Livermorium", atomic_weight: 293.0, period: 7, group: "VIA" },
    Element { atomic_number: 117, symbol: "Ts", name: "鿬", pronunciation: "tián", english_name: "Tennessine", atomic_weight: 294.0, period: 7, group: "VIIA" },
    Element { atomic_number: 118, symbol: "Og", name: "鿫", pronunciation: "ào", english_name: "Oganesson", atomic_weight: 294.0, period: 7, group: "0族" },
];

pub fn get_element_by_name(name: &str) -> Option<&'static Element> {
    PERIODIC_TABLE.iter().find(|e| e.name == name)
}

pub fn get_element_by_position(position: u8) -> Option<&'static Element> {
    PERIODIC_TABLE.iter().find(|e| e.atomic_number == position)
}
