name: Auto Merge

on:
  pull_request_target:
    types: [opened, synchronize]

jobs:
  automerge:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'automerge')
    steps:
      - name: Auto merge
        uses: "pascalgn/merge-action@v0.15.6"
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          merge_method: "squash"
