name: Dependency Updates

on:
  schedule:
    # Run weekly on Sundays at 2 AM UTC
    - cron: "0 2 * * 0"
  workflow_dispatch: # Allow manual triggering

permissions:
  contents: write
  pull-requests: write

jobs:
  update-python:
    name: Update Python Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install pip-tools
        run: pip install pip-tools

      - name: Update Python dependencies
        run: |
          cd hello-mcp-python
          if [ -f requirements.txt ]; then
            pip-compile --upgrade requirements.in || pip-compile --upgrade --generate-hashes requirements.txt || echo "No requirements.in found, using existing requirements.txt"
          fi

      - name: Create Python PR
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore(python): update dependencies"
          title: "chore(python): update dependencies"
          body: |
            This PR updates Python dependencies to their latest versions.

            - Auto-generated by GitHub Actions
            - Please review the changes before merging
          branch: update-python-deps
          base: main
          labels: |
            dependencies
            python
            auto-merge

  update-nodejs:
    name: Update Node.js Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: hello-mcp-ts/package-lock.json

      - name: Update Node.js dependencies
        run: |
          cd hello-mcp-ts
          npm update
          npm audit fix || true

      - name: Create Node.js PR
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore(nodejs): update dependencies"
          title: "chore(nodejs): update dependencies"
          body: |
            This PR updates Node.js dependencies to their latest versions.

            - Auto-generated by GitHub Actions
            - Please review the changes before merging
          branch: update-nodejs-deps
          base: main
          labels: |
            dependencies
            nodejs
            auto-merge

  update-rust:
    name: Update Rust Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install cargo-edit
        run: cargo install cargo-edit

      - name: Update Rust dependencies
        run: |
          cd hello-mcp-rust
          cargo upgrade

      - name: Create Rust PR
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore(rust): update dependencies"
          title: "chore(rust): update dependencies"
          body: |
            This PR updates Rust dependencies to their latest versions.

            - Auto-generated by GitHub Actions
            - Please review the changes before merging
          branch: update-rust-deps
          base: main
          labels: |
            dependencies
            rust
            auto-merge

  update-java:
    name: Update Java Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Update Java dependencies
        run: |
          cd hello-mcp-java
          # Use Maven versions plugin to update dependencies
          mvn versions:use-latest-versions -DallowSnapshots=false
          mvn versions:commit

      - name: Create Java PR
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore(java): update dependencies"
          title: "chore(java): update dependencies"
          body: |
            This PR updates Java/Maven dependencies to their latest versions.

            - Auto-generated by GitHub Actions
            - Please review the changes before merging
          branch: update-java-deps
          base: main
          labels: |
            dependencies
            java
            auto-merge

  update-kotlin:
    name: Update Kotlin Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Update Kotlin dependencies
        run: |
          cd hello-mcp-kotlin
          # Use Gradle versions plugin if available
          ./gradlew dependencyUpdates || echo "No dependency updates plugin found"

      - name: Create Kotlin PR
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore(kotlin): update dependencies"
          title: "chore(kotlin): update dependencies"
          body: |
            This PR updates Kotlin/Gradle dependencies to their latest versions.

            - Auto-generated by GitHub Actions
            - Please review the changes before merging
          branch: update-kotlin-deps
          base: main
          labels: |
            dependencies
            kotlin
            auto-merge

  update-csharp:
    name: Update C# Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0"

      - name: Update C# dependencies
        run: |
          cd hello-mcp-csharp
          # Update NuGet packages
          dotnet list package --outdated
          dotnet add package Microsoft.Extensions.Hosting --version latest || true

      - name: Create C# PR
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore(csharp): update dependencies"
          title: "chore(csharp): update dependencies"
          body: |
            This PR updates C#/.NET dependencies to their latest versions.

            - Auto-generated by GitHub Actions
            - Please review the changes before merging
          branch: update-csharp-deps
          base: main
          labels: |
            dependencies
            csharp
            auto-merge

  update-swift:
    name: Update Swift Dependencies
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Swift
        uses: swift-actions/setup-swift@v1
        with:
          swift-version: "5.9"

      - name: Update Swift dependencies
        run: |
          cd hello-mcp-swift
          swift package update

      - name: Create Swift PR
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore(swift): update dependencies"
          title: "chore(swift): update dependencies"
          body: |
            This PR updates Swift Package Manager dependencies to their latest versions.

            - Auto-generated by GitHub Actions
            - Please review the changes before merging
          branch: update-swift-deps
          base: main
          labels: |
            dependencies
            swift
            auto-merge
